name: Sanity Webhook - Auto Deploy

on:
  repository_dispatch:
    types: [sanity-content-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PDMSITE_0903 }}'
          projectId: pdmsite-0903
          channelId: live

      - name: Notify deployment
        run: |
          echo "🚀 Site deployed successfully after Sanity content update!"
          echo "📅 Deployment time: $(date)" 